version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres 
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5416:5432"  # Map host port 5432 to container port 5416
  go-microservice:
    image: rockenscdev/go-microservice-test-image:latest
    environment: 
      APP_DB_USERNAME: postgres
      APP_DB_PASSWORD: postgres
      APP_DB_PORT: 5416
      APP_DB_NAME: postgres
    ports:
      - "9090:8888"  # Map host port 9090 to container port 8888