# CI-CD Exercise 03 (accompanying Chapter „Continuous Integration“) - Lukas Rockenschaub
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_DB_USERNAME: postgres
  APP_DB_PASSWORD: postgres
  APP_DB_NAME: postgres

  TEST_DB_USERNAME: postgres
  TEST_DB_PASSWORD: postgres
  TEST_DB_NAME: postgres

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.22.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    # Start postgresql docker container
    - name: Start postgresql Container
      run: docker run postgres:latest --name postgres -p 5416:5432 -e POSTGRES_PASSWORD=${APP_DB_PASSWORD} -e POSTGRES_USER=${APP_DB_USERNAME} -e POSTGRES_DB=${APP_DB_NAME} 

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  
  sonarCloud:
    needs: build_and_test
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  docker_build_and_publish:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - uses: actions/checkout@v3
    - id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Docker Login 
      uses: docker/login-action@v2.1.0
      with: 
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker Image
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/go-microservice-test-image:latest,${{ secrets.DOCKERHUB_USER }}/go-microservice-test-image:${{ steps.vars.outputs.sha_short }}
  